"""
Web Chat Bot -- FastAPI server that exposes the support agent via HTTP.
Run: python web_bot.py
Visit: http://localhost:8001

This is the backend for the chat widget (static/index.html).
It handles incoming messages from the browser, passes them to agent.py,
and returns the response as JSON.

Port: 8001 (not 8000 -- avoids conflicts with other local servers)
"""

import os
import uuid
import urllib.request
import json
from pathlib import Path
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel
from dotenv import load_dotenv

load_dotenv()

# Import the agent's chat function
import sys
sys.path.insert(0, str(Path(__file__).parent))
from agent import build_agent

app = FastAPI(title="Support Agent Web API")

# Allow requests from any origin (so the widget works on any client website)
# In production, replace "*" with your actual domain for security:
# allow_origins=["https://yoursite.com"]
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["POST", "GET"],
    allow_headers=["*"],
)

# Serve static files (the chat widget HTML)
static_dir = Path(__file__).parent / "static"
static_dir.mkdir(exist_ok=True)
app.mount("/static", StaticFiles(directory=str(static_dir)), name="static")

# Build the agent once at startup
# This loads your KB and system prompt into memory -- happens only once
chain = build_agent()

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
ESCALATION_CHAT_ID = os.getenv("ESCALATION_CHAT_ID", "")


def notify_escalation_web(session_id: str, message: str, reason: str):
    """Send escalation alert to owner via Telegram when triggered from web chat."""
    if not TELEGRAM_BOT_TOKEN or not ESCALATION_CHAT_ID:
        return
    alert = (
        f"ESCALATION NEEDED\n\n"
        f"Platform: WEB CHAT\n"
        f"Session: {session_id[:8]}...\n"
        f"Message: {message}\n"
        f"Reason: {reason}\n\n"
        f"No direct link available -- check your website's live chat or follow up via email/phone."
    )
    payload = json.dumps({"chat_id": ESCALATION_CHAT_ID, "text": alert}).encode("utf-8")
    req = urllib.request.Request(
        f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        urllib.request.urlopen(req, timeout=10)
    except Exception:
        pass  # Don't crash the bot if the alert fails


class ChatRequest(BaseModel):
    message: str
    session_id: str  # UUID generated by the browser, unique per visitor


class ChatResponse(BaseModel):
    reply: str
    escalated: bool = False


@app.get("/")
async def root():
    """Serve the chat widget demo page."""
    return FileResponse(str(static_dir / "index.html"))


@app.get("/health")
async def health():
    """Health check endpoint -- useful for monitoring and Railway deployments."""
    return {"status": "ok"}


@app.post("/chat", response_model=ChatResponse)
async def chat(req: ChatRequest):
    """
    Main chat endpoint. Receives a message and returns the agent's response.

    The browser sends:
        { "message": "What are your hours?", "session_id": "uuid-here" }

    This returns:
        { "reply": "We're open 10am-8pm...", "escalated": false }
    """
    session_id = f"web:{req.session_id}"
    try:
        result = chain.invoke(
            {"input": req.message},
            config={"configurable": {"session_id": session_id}},
        )
        reply = result.content if hasattr(result, "content") else str(result)
        escalated = reply.upper().startswith("ESCALATE")
        if escalated:
            reason = reply.split("--", 1)[-1].strip() if "--" in reply else "Needs human support"
            notify_escalation_web(req.session_id, req.message, reason)
            reply = "I'm connecting you with a team member right now. Someone will be with you shortly."
        return ChatResponse(reply=reply, escalated=escalated)
    except Exception as e:
        return ChatResponse(reply="Sorry, something went wrong. Please try again.", escalated=False)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8001)
